services:
  web:
    container_name: ${PROJECT_NAME}_web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${PORT}
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
