# Generated by Django 5.2.5 on 2025-08-25 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',), 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'verbose_name': 'Dars materiali', 'verbose_name_plural': 'Dars materiallari'},
        ),
        migrations.AlterModelOptions(
            name='lessonquiz',
            options={'verbose_name': 'Dars testi', 'verbose_name_plural': 'Dars testlari'},
        ),
        migrations.AlterModelOptions(
            name='lessonquizquestion',
            options={'verbose_name': 'Test savoli', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.AlterModelOptions(
            name='lessonquizquestionanswer',
            options={'verbose_name': 'Savol javobi', 'verbose_name_plural': 'Savol javoblari'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('semester', 'group'), 'verbose_name': 'Semestr', 'verbose_name_plural': 'Semestrlar'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Talaba guruhi', 'verbose_name_plural': 'Talaba guruhlari'},
        ),
        migrations.AlterModelOptions(
            name='studentlessonquiz',
            options={'verbose_name': 'Talaba testi', 'verbose_name_plural': 'Talaba testlari'},
        ),
        migrations.AlterModelOptions(
            name='studentlessonquizanswer',
            options={'verbose_name': 'Talaba javobi', 'verbose_name_plural': 'Talaba javoblari'},
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentlessonquiz',
            unique_together={('quiz', 'student')},
        ),
    ]
