# Generated by Django 5.2.5 on 2025-08-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_lesson_options_alter_lessonmaterial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='file_type',
            new_name='course',
        ),
    ]
