# Generated by Django 5.2.5 on 2025-08-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_file_type_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Tugatildi'),
        ),
    ]
