# Generated by Django 5.2.5 on 2025-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_semester_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz_duration',
            field=models.DurationField(null=True, verbose_name='Test davomiyligi'),
        ),
    ]
