# Generated by Django 5.2.5 on 2025-08-28 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_lesson_quiz_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='self_work',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='total',
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.IntegerField(default=0, verbose_name='Dars soati')),
                ('practice', models.IntegerField(default=0, verbose_name='Amaliyot soati')),
                ('self_work', models.IntegerField(default=0, verbose_name='Mustaqil ish soati')),
                ('total', models.IntegerField(default=0, verbose_name='Jami soat')),
                ('credit', models.IntegerField(default=0, verbose_name='Kredit')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.semester')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semestr',
                'verbose_name_plural': 'Semestrlar',
                'ordering': ('semester__order',),
            },
        ),
    ]
