# Generated by Django 5.2.5 on 2025-08-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='semester',
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='management.semestersubject'),
        ),
    ]
