# Generated by Django 5.2.5 on 2025-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_lesson_semester_lesson_semester_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('order',), 'verbose_name': 'Semestr', 'verbose_name_plural': 'Semestrlar'},
        ),
        migrations.AlterModelOptions(
            name='semestersubject',
            options={'ordering': ('semester__order',), 'verbose_name': 'Semestr fani', 'verbose_name_plural': 'Semestr fanlari'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
